services:
  maestro:
    image: nginx:latest
    ports:
    - 1010:80

    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  worker00:
    image: hashicorp/http-echo
    command: "-text='-> worker00'"
  worker01:
    image: hashicorp/http-echo
    command: "-text='-> worker01'"
  worker02:
    image: hashicorp/http-echo
    command: "-text='-> worker02'"
  client0:
    image: client:latest
  client1:
    image: client:latest
  client2:
    image: client:latest
  client3:
    image: client:latest
  client4:
    image: client:latest

  plankton:
    image: crcardd/plankton:latest
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - 5555:5032
