events {
    worker_connections 1024;
}

http {
    upstream apiapi {
        server worker00:5678;
        server worker01:5678;
        server worker02:5678;
    }

    server {
        listen 80;
        location /api {
            proxy_pass http://apiapi;
        }
    }
}