services:
    api:
        build: .
            # dockerfile: Dockerfile
            # context: ./
        ports:
         - 1919:5184
        env_file:
         - .env
        
#         volumes:
#          - bancodedados:/app
    db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_PID=Developer
            - MSSQL_SA_PASSWORD=821hs91ukd_uwq&1*9j

        volumes:
            - bancodedados:/var/opt/mssql

    maestro:
        image: nginx:latest
        ports:
        - 80:5184

        volumes:
            - /Aula03/nginx.conf:/etc/nginx/nginx.conf:ro

    worker00:
        image: hashicorp/http-echo
        command: "-text='mensage ai'"

    worker01:
        image: hashicorp/http-echo
        command: "-text='outro'"
    worker02:
        image: hashicorp/http-echo
        command: "-text='simsim'"

volumes:
    bancodedados: