events {
    worker_connections 1024;
}

http {
    upstream apiapi {
        server api1:1919
        server api2:1919
        server api3:1919
        server api4:1919
        server api5:1919
        server api6:1919
    };

    server {
        listen 80;
        location /api {
            proxy_pass http://apiapi;
        }
    }
}